**1. Eigen Values and Eigen Vectors**

In [ ]:
import numpy as np
from sympy import *
from fractions import Fraction
from math import gcd
from sklearn.preprocessing import normalize

In [ ]:
matrix = np.array([[4, 0, 1], [-2, 1, 0], [-2, 0, 1]])
# matrix = np.array([[-5, 2], [-7, 4]])

l = symbols('lambda')
order = len(matrix)
I = np.identity(order, dtype = int)
lI = I * l
expr = Matrix(lI - matrix).det()
eigValues = solve(expr)

eigVectors = []
zeros = np.zeros((order, 1), dtype = int)
for e in eigValues:
  m = (e * I) - matrix
  m = Matrix(m)
  aug = m.rref()[0]
  vec, params = aug.gauss_jordan_solve(Matrix([0] * order))
  taus_ones = {tau:1 for tau in params}
  vec = vec.xreplace(taus_ones)
  eigVectors.append(np.array(vec))

for i in range(len(eigValues)):
  lcm = 1
  denominators = [Fraction(x).denominator() for x in eigVectors[i].flatten()]
  for j in denominators:
    lcm = lcm * j // gcd(lcm, j)
  eigVectors[i] = eigVectors[i] * lcm

for i in range(len(eigValues)):
  print("Eigen Value:\n", eigValues[i], "\n", "Eigen Vector:\n", eigVectors[i], "\n", sep = "")

Eigen Value:
1
Eigen Vector:
[[0]
 [1]
 [0]]

Eigen Value:
2
Eigen Vector:
[[-1]
 [2]
 [2]]

Eigen Value:
3
Eigen Vector:
[[-1]
 [1]
 [1]]



**2. Diagonalize the Matrix**

In [ ]:
def eigenValues(matrix):
  l = symbols('lambda')
  order = len(matrix)
  I = np.identity(order, dtype = int)
  lI = I * l
  expr = Matrix(lI - matrix).det()
  eigValues = solve(expr)

  return eigValues

In [ ]:
def eigenVectors(matrix, eigValues):
  eigVectors = []
  order = len(matrix)
  I = np.identity(order, dtype = int)
  zeros = np.zeros((order, 1), dtype = int)

  for e in eigValues:
    m = (e * I) - matrix
    m = Matrix(m)
    aug = m.rref()[0]
    vec, params = aug.gauss_jordan_solve(Matrix([0] * order))
    taus_ones = {tau:1 for tau in params}
    vec = vec.xreplace(taus_ones)
    eigVectors.append(np.array(vec))

  for i in range(len(eigValues)):
    lcm = 1
    denominators = [Fraction(x).denominator() for x in eigVectors[i].flatten()]
    for j in denominators:
      lcm = lcm * j // gcd(lcm, j)
    eigVectors[i] = eigVectors[i] * lcm

  return eigVectors

In [ ]:
matrix = np.array([[5, -3], [6, -4]])
eValues = eigenValues(matrix)
eVectors = eigenVectors(matrix, eValues)

P = Matrix(eVectors[0])
for i in range(1, len(eVectors)):
  P = P.col_insert(i, Matrix(eVectors[i]))
  
D = P.inv() * matrix * P
D = np.array(D)

print("The diagonal matrix is:\n", D)

# OR
# D2 = []
# for i in range(len(eValues)):
#   l = []
#   for j in range(len(eValues)):
#     if i == j:
#       l.append(eValues[i])
#     else:
#       l.append(0)
#   D2.append(l)
# D2 = np.array(D2)

# print(D2)

The diagonal matrix is:
 [[-1 0]
 [0 2]]


**3. Quadratic Form to Canonical Form**
(Orthogonal Diagonalization)

In [ ]:
# matrix = np.array([[1, -1, 0], [-1, 2, 1], [0, 1, 1]])
matrix = np.array([[0, 3], [3, 0]])

eValues = eigenValues(matrix)
eVectors = eigenVectors(matrix, eValues)

P = Matrix(eVectors[0])
for i in range(1, len(eVectors)):
  P = P.col_insert(i, Matrix(eVectors[i]))
  
D = P.inv() * matrix * P

x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
# X = Matrix([[x, y, z]])
X = Matrix([[x, y]])
canonical = X * D * transpose(X)
print(np.array(canonical))

[[-3*x**2 + 3*y**2]]


**4. Check Diagonizability**

In [ ]:
matrix = np.array([[-10, 11, -6], [-15, 16, -10], [-3, 3, -2]])
order = len(matrix)

eValues = set(eigenValues(matrix))

if len(eValues) == order:
  print("Diagonizable")
else:
  print("Not Diagonizable")

Not Diagonizable


**5. Find Dominant Eigen Vector**

In [ ]:
def normalize(x):
  max = abs(x).max()
  newX = x / x.max()
#   print(max, newX)

  return max, newX

In [ ]:
# matrix = np.array([[2, 3], [4, 10]])
matrix = np.array([[2, 1], [0, -4]])

order = len(matrix)
x = np.ones((order, 1), dtype = int)

for i in range(8):
  x = np.dot(matrix, x)
  l, x = normalize(x)

print("Eigenvalue:", l)
print("Eigenvector:", x)

Eigenvalue: 22.755555555555556
Eigenvector: [[-0.16210938]
 [ 1.        ]]


**6. Smallest Eigen Vector**

In [ ]:
matrix = [[10, -8, -4], [-8, 13, 4], [-4, 5, 4]]
eValues = eigenValues(matrix)
# minE = min(eValues)
minE = 1.9

order = len(matrix)
I = np.identity(order, dtype = int)
lI = I * minE
x = np.ones((order, 1), dtype = int)
mu = 0
v = 0

for i in range(5):
    y = np.linalg.inv(matrix - lI) * x
    mu = np.amax(y)
    v = minE + 1 / mu
    x = (1 / mu) * y

print(v)

2.008490930142802
